<?php

declare(strict_types=1);

namespace App\Application\Api\V1\Controllers;

use App\Application\Api\V1\Controllers\Concerns\ReadsAuditTrail;
use App\Application\Api\V1\Requests\Audit\ActivityLogFilterRequest;
use App\Application\Api\V1\Requests\Customer\StoreCustomerRequest;
use App\Application\Api\V1\Requests\Customer\UpdateCustomerRequest;
use App\Application\Api\V1\Requests\SetActivationRequest;
use App\Application\Api\V1\Resources\CustomerResource;
use App\Application\Controller;
use App\Domain\Audit\AuditService;
use App\Domain\Customer\CustomerService;
use App\Domain\Customer\DTOs\CustomerData;
use App\Domain\Customer\Models\Customer;
use App\Domain\Customer\Queries\CustomerFilters;
use App\Domain\Identity\Enums\PermissionName;
use App\Domain\Order\Queries\OrderCountsByCustomerQuery;
use App\Support\ResponseTrait;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Customers
 *
 * Customers of the printing business and the shops they sell from.
 *
 * Each customer gets a permanent code of the form `C1`, `C2`, `C3` … derived from their id.
 * It is assigned by the server and cannot be sent or changed by a client.
 */
class CustomerController extends Controller
{
    use ReadsAuditTrail, ResponseTrait;

    public function __construct(private readonly CustomerService $customers) {}

    /**
     * List customers
     *
     * Newest first. `search` matches the name, the code, or the phone number.
     *
     * Each row carries `orders_count` — how many orders that customer has ever placed,
     * cancellations included — for callers holding `orders.view`. Everyone else gets no such
     * key, which is a different fact from a zero and is why it is omitted rather than nulled.
     *
     * Two options read the orders rather than the customers, and both need `orders.view`:
     *
     * - `has_orders` — `0` for the customers who have never ordered, «زبائن بدون طلب», and `1`
     *   for «لديهم طلبات». Left out, the list is everybody. A cancelled order still counts as
     *   one, exactly as it does in `orders_count`; a deleted one does not.
     * - `sort=least_recent_order` — the longest since their last order first, so the customers
     *   worth ringing are at the top. Those who never ordered come last, and every row on this
     *   sort carries `last_order_at` (null for them).
     */
    public function index(Request $request): JsonResponse
    {
        $filters = CustomerFilters::fromArray($request->only(['search', 'is_active', 'has_orders', 'sort']));

        // Refused, not quietly answered without it. Omitting `orders_count` for this reader is
        // honest — they did not ask for it — but a page that dropped a filter they *did* ask for
        // would be the wrong answer to their question wearing a 200.
        if ($filters->readsOrders() && ! $this->maySeeOrders($request)) {
            return $this->error('لا تملك صلاحية عرض الطلبيات', 403);
        }

        $perPage = min(max((int) $request->integer('per_page', 15), 1), 100);

        $customers = $this->customers->paginate($filters, $perPage);

        // `items()`, which the paginator *contract* declares — the models come back by
        // reference, so stamping them here is stamping what the resource is about to render.
        $this->attachOrderCounts($request, $customers->items());

        return $this->successWithPagination(CustomerResource::collection($customers));
    }

    /**
     * Create a customer
     *
     * Shops may be supplied inline. The `code` is generated by the server.
     */
    public function store(StoreCustomerRequest $request): JsonResponse
    {
        $customer = $this->customers->create(CustomerData::fromArray($request->validated()));

        return $this->created(new CustomerResource($customer), 'تم إضافة العميل بنجاح');
    }

    /**
     * Get one customer
     *
     * Carries `orders_count` on the same terms as the list — see there.
     */
    public function show(Request $request, Customer $customer): JsonResponse
    {
        $customer->load(Customer::SHOP_RELATIONS);

        $this->attachOrderCounts($request, [$customer]);

        return $this->success(new CustomerResource($customer));
    }

    /**
     * Update a customer
     *
     * Sending `shops` replaces the whole set: entries with an `id` are updated, entries
     * without one are added, and any shop left out is removed. Omit `shops` entirely to
     * leave them untouched.
     */
    public function update(UpdateCustomerRequest $request, Customer $customer): JsonResponse
    {
        $updated = $this->customers->update($customer, CustomerData::fromArray($request->validated()));

        return $this->success(new CustomerResource($updated), 'تم تحديث بيانات العميل بنجاح');
    }

    /**
     * Activate or deactivate a customer
     *
     * Customers are never deleted — deactivating keeps their history intact.
     */
    public function setActivation(SetActivationRequest $request, Customer $customer): JsonResponse
    {
        $updated = $this->customers->setActive($customer, $request->boolean('is_active'));

        return $this->success(
            new CustomerResource($updated),
            $updated->is_active ? 'تم تنشيط العميل' : 'تم إلغاء تنشيط العميل',
        );
    }

    /**
     * A customer's history
     *
     * Every change to the customer and to their shops, newest first — who made it and what it
     * was before. Shops are included because they are edited through the customer and have no
     * screen of their own.
     *
     * Filter with `event`, `causer_id`, `from` and `to`.
     */
    public function logs(ActivityLogFilterRequest $request, Customer $customer, AuditService $audit): JsonResponse
    {
        return $this->auditTrailResponse($request, $customer, $audit);
    }

    /**
     * Stamps `orders_count` onto customers about to be rendered, for readers allowed to see it.
     *
     * **Here rather than in the resource, because this is an authorization decision.** Somebody
     * holding `customers.view` and not `orders.view` may read who a customer is without being
     * told how much business they do; the resource leaves the key out entirely when nothing was
     * stamped, so the app gets no key rather than a nought it would print on the card.
     *
     * **And here rather than as a `withCount` on the query, because `Customer` has no `orders()`
     * relation on purpose** — see {@see OrderCountsByCustomerQuery}. Only the create and update
     * responses go without: nobody reads a count off the form they have just saved.
     *
     * @param  list<Customer>  $customers
     */
    private function attachOrderCounts(Request $request, array $customers): void
    {
        if ($customers === [] || ! $this->maySeeOrders($request)) {
            return;
        }

        $counts = (new OrderCountsByCustomerQuery)(
            array_map(static fn (Customer $customer): int => $customer->id, $customers),
        );

        foreach ($customers as $customer) {
            $customer->setAttribute('orders_count', $counts[$customer->id] ?? 0);
        }
    }

    /**
     * Whether this reader is allowed to be told anything the orders know.
     *
     * One method for the two things that turn on it — the count that is stamped on, and the
     * filters that are refused — so a third cannot be added while reading the permission from a
     * different place.
     */
    private function maySeeOrders(Request $request): bool
    {
        return $request->user()?->can(PermissionName::ViewOrders->value) === true;
    }
}
